apiVersion: apps/v1

kind: Deployment

metadata:

  name: webapp

  labels:

    app: web

spec:

  replicas: 2

  selector:

    matchLabels:

      app: web

  template:

    metadata:

      labels:

        app: web

    spec:

      containers:

        - name: webapp

          image: nginx

          ports: veduruchandrashekar/hr-api:latest

            - containerPort: 8080
