apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: hr-api
  template:
    metadata:
      labels:
        app: hr-api
    spec:
      containers:
      - image: veduruchandrashekar/hr-api:latest
        name: hr-api
        ports:
        - containerPort: 8080
