apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp3
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: nodeapp3
  template:
    metadata:
      labels:
        app: nodeapp3
    spec:
      containers:
      - image: veduruchandrashekar/hr-api:latest
        name: nodeapp3
        ports:
        - containerPort: 8080
