kind: Deployment
apiVersion: v1
metadata:
name: nodapp
spec:
replicas: 1
template:
metadata:
labels:
app: webservers
spec:
containers:
- name: nodapp
image: veduruchandrashekar/hr-api:latest
ports:
- containerPort: 8080
