kind: Deployment
apiVersion: apps/v1beta1
metadata:
name: my-httpd
spec:
replicas: 1
template:
metadata:
labels:
app: webservers
spec:
containers:
- name: my-httpd-container1
image: veduruchandrashekar/hr-api:latest
ports:
- containerPort: 8080
