apiVersion: v1
kind: Pod
metadata:
  name: nodeapp2
  labels:
    app: nodeapp2
spec:
  containers:
    - name: nodeapp2
      image: veduruchandrashekar/hri-api:latest
      ports:
        - containerPort: 8080
