apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hr-api
spec:
  replicas: 3
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [hr-api]}
  template:
    metadata:
      name: hr-api
      labels:
        app: hr-api
    spec:
      containers:
      - name: hr-api
        image: veduruchandrashekar/hr-api:latest
        ports:
        - containerPort: 8080
