apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodeapp
spec:
  replicas: 5
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [nodeapp]}
  template:
    metadata:
      name: nodeapp
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: veduruchandrashekar/hr-api:latest
        ports:
        - containerPort: 8080
